"""hypotheses.py — WHAT WINS, as a hypothesis space over allocentric world-states.

WHY IT LIVES HERE AND NOT IN A COLUMN. A win condition can involve the BODY ("the agent is on the goal AND the block is
on the pad"), and the task column deliberately excludes the self: putting it in re-mints a task state on every step and
re-creates exactly the joint-state blow-up H0 was built to measure (tried, and `test_task_column` fails). The allocentric
world-state DOES bind self-location to what is where — `WorldMap.agent` beside `WorldMap.objects` — and binding a place
to what is there, across frames, is the hippocampus's job
(`reference_tbt_frames_and_hippocampus`: no hippocampus until episodic/cross-frame binding).

WHY NOT A RULE GRAMMAR. The agent used to generate candidates with `_winning_conditions`: "a mover resting on a static
landmark, and/or the self on a landmark". That is the rule proposer this project already deleted once
(`agent.py`, 2026-07-23: "a rule GRAMMAR nobody justified — two objects co-located — which cannot state CollectAll's
tour, let alone a contradiction between a testimony and an autopsy report"). It survived under another name because it
fed `goal_mem` rather than `_act`. Here nothing is privileged: a FACT is a coincidence between ANY ordered pair of things
in the world-state, the self included, and no rule says which pairs may matter.

WHERE HYPOTHESES COME FROM, and this is the part that took two wrong turns. Not from remembered PAYING episodes — on a
fresh game there are none, which is the normal case for ARC and exactly what LockPath L2 measured (zero paying steps in
150). Not from remembered episodes generally either — every one of those is a NON-paying state, so every hypothesis drawn
from them is refuted the moment it forms, which is the Warehouse result where the whole space emptied. They come from
**IMAGINED REACHABLE STATES**: the forward model rolled forward to somewhere the agent has not been. L hypothesises about
someone he has never met, then tests.

That also keeps satisfiability free, which is why no logical-consistency filter is needed: an imagined state is generated
BY the forward model, so it is reachable by construction. A grammar would need such a filter, because most
syntactically-valid predicates are unsatisfiable ("the block is at (3,4) and at (5,2)") — and its filters are then where
domain knowledge hides.

THE REFUTATION CRITERION, with no threshold in it. A hypothesis is a SET OF FACTS; it HOLDS in a state when every one of
its facts is true there — plain containment, no overlap constant. So visiting a non-paying state refutes every hypothesis
that state satisfies, which is every subset of its facts, all at once. Non-payment is the abundant observation and it does
the most work.

THE SPACE IS TRACKED IMPLICITLY, never enumerated. A fact-set survives iff it is not contained in any visited non-paying
state — which is true iff at least one of its facts has never been observed true. So the surviving space is GENERATED by
the facts not yet made true, and tracking those tracks the space. Enumerating subsets would be the wrong design, and
capping the enumeration with a constant would be worse.
"""
from __future__ import annotations

import math


def world_facts(world, kinds=None) -> frozenset:
    """Every COINCIDENCE in an allocentric world-state, as `(kind_a, kind_b, integer displacement)` over ordered pairs.

    The agent participates under the kind `"self"`, so a win involving the body is statable without the body entering any
    column's configuration. Displacement is quantised to cells; absolute position never appears, so a fact is invariant to
    translating the whole board — the same property that makes a task state position-free."""
    kinds = kinds or {}
    items = []
    if getattr(world, "agent", None) is not None:
        items.append(("self", tuple(int(round(c)) for c in world.agent[0])))
    for oid, pose in getattr(world, "objects", {}).items():
        items.append((kinds.get(oid, oid), tuple(int(round(c)) for c in pose[0])))
    # STATICS too. A world-state keeps movers in `objects` and landmarks in `static` (cell -> feature) because the ROLLOUT
    # only simulates bodies — but a win condition is routinely about a landmark ("the block is on the PAD"), so both
    # containers are read here. Which container a thing sits in is a fact about who simulates it, not about what may be a
    # condition, and nothing is privileged in this vocabulary.
    for cell, kind in (getattr(world, "static", None) or {}).items():
        items.append((kind, tuple(int(round(c)) for c in cell)))
    out = set()
    for ka, pa in items:
        for kb, pb in items:
            if ka is kb and pa == pb:
                continue
            out.add((ka, kb, tuple(b - a for a, b in zip(pa, pb))))
    return frozenset(out)


class WinHypotheses:
    """The hypothesis space for "what pays", over world-state facts.

    `seen` are facts observed true in a state that paid NOTHING — every hypothesis they contain is refuted, since it held
    and no reward came. `confirmed` is the Find-S intersection over PAYING states: the facts common to every payment,
    which is the most specific description consistent with all positive evidence. Generalisation is intersection, which
    preserves satisfiability (both episodes remain witnesses), so no consistency check is ever needed."""

    def __init__(self) -> None:
        self.seen: set = set()               # facts observed true while NOTHING was paid → refuted as sufficient
        self.confirmed = None                # Find-S: facts common to every paying state (None = no payment yet)
        self.too_general = False             # `confirmed` held somewhere that paid nothing ⇒ mint a finer distinction
        self.n_paid = 0

    def observe(self, facts, paid: bool) -> None:
        """One outcome. A payment GENERALISES the confirmed description; a non-payment REFUTES everything the state
        satisfies, and additionally disproves `confirmed` itself if that held here too."""
        facts = frozenset(facts)
        if paid:
            self.n_paid += 1
            self.confirmed = frozenset(facts) if self.confirmed is None else (self.confirmed & facts)
            return
        self.seen |= facts
        if self.confirmed is not None and self.confirmed <= facts:
            self.too_general = True          # satisfied without payment ⇒ not a conjunction of coincidences at this grain

    def live(self, reachable) -> frozenset:
        """The surviving hypotheses, as the facts that GENERATE them: those an imagined reachable state can make true and
        that have never been observed true. Anything already seen without payment is refuted, and so is every fact-set
        built only from such facts."""
        return frozenset(reachable) - self.seen

    def bits(self, reachable) -> float:
        """`log2` of the surviving space. Each unmade fact is one independent thing still to try."""
        n = len(self.live(reachable))
        return math.log2(n) if n > 1 else 0.0

    def holds(self, facts) -> bool:
        """Does the confirmed win condition hold in a state? Plain containment — the criterion with no constant in it."""
        return self.confirmed is not None and self.confirmed <= frozenset(facts)
