"""
Motor control systems: mouse and keyboard control via active inference.

In active inference, motor commands emerge from prediction errors in proprioception.
When the network predicts the cursor should be at position P but proprioception
reports it's at position Q, the error signal (P - Q) drives movement to make
reality match prediction.
"""

import time
import numpy as np
from typing import Tuple, Optional, Set, Callable
from pynput import mouse, keyboard
from collections import deque
import threading


class MouseController:
    """
    Mouse control via active inference.

    Motor commands are generated by prediction errors: when the predicted
    cursor position differs from the actual position, movement is triggered
    to minimize the error.

    Attributes:
        gain: Multiplier for cursor prediction errors (controls movement speed)
        click_threshold: Threshold for click neuron activation
        controller: pynput mouse controller
        screen_width: Screen width in pixels
        screen_height: Screen height in pixels
    """

    def __init__(
        self,
        screen_width: int,
        screen_height: int,
        gain: float = 5.0,
        click_threshold: float = 0.7,
        rate_limit_hz: float = 60.0,
        constrain_bounds: Optional[Tuple[int, int, int, int]] = None
    ):
        """
        Initialize mouse controller.

        Args:
            screen_width: Screen width in pixels
            screen_height: Screen height in pixels
            gain: Cursor movement gain (multiplier for position errors)
            click_threshold: Threshold for triggering clicks (0-1 range)
            rate_limit_hz: Maximum update rate in Hz
            constrain_bounds: Optional (left, top, right, bottom) pixel bounds
                            to constrain cursor movement for safety
        """
        self.screen_width = screen_width
        self.screen_height = screen_height
        self.gain = gain
        self.click_threshold = click_threshold
        self.rate_limit_hz = rate_limit_hz
        self.min_update_interval = 1.0 / rate_limit_hz
        self.constrain_bounds = constrain_bounds

        # Initialize pynput controller
        self.controller = mouse.Controller()

        # Last update time for rate limiting
        self.last_update_time = 0.0

        # Movement statistics
        self.movements = deque(maxlen=100)
        self.clicks = deque(maxlen=100)

        # Safety: Emergency stop flag
        self.enabled = True

    def update_from_error(
        self,
        cursor_error: np.ndarray,
        click_signal: float,
        dt: float = 1.0
    ) -> None:
        """
        Update cursor position and clicks from prediction errors.

        Args:
            cursor_error: Prediction error in normalized coordinates [dx, dy].
                         cursor_error = predicted_position - current_position
            click_signal: Click activation (0-1). Click triggered if > threshold
            dt: Time step (default 1.0)
        """
        if not self.enabled:
            return

        # Rate limiting
        current_time = time.time()
        if current_time - self.last_update_time < self.min_update_interval:
            return
        self.last_update_time = current_time

        # Convert normalized error to pixel movement
        dx_pixels = cursor_error[0] * self.screen_width * self.gain * dt
        dy_pixels = cursor_error[1] * self.screen_height * self.gain * dt

        # Get current position
        current_x, current_y = self.controller.position

        # Calculate new position
        new_x = current_x + dx_pixels
        new_y = current_y + dy_pixels

        # Apply constraints if specified
        if self.constrain_bounds is not None:
            left, top, right, bottom = self.constrain_bounds
            new_x = np.clip(new_x, left, right)
            new_y = np.clip(new_y, top, bottom)
        else:
            # Constrain to screen bounds
            new_x = np.clip(new_x, 0, self.screen_width - 1)
            new_y = np.clip(new_y, 0, self.screen_height - 1)

        # Move cursor
        if abs(dx_pixels) > 0.1 or abs(dy_pixels) > 0.1:  # Minimum movement threshold
            self.controller.position = (int(new_x), int(new_y))
            self.movements.append((dx_pixels, dy_pixels, current_time))

        # Handle click
        if click_signal > self.click_threshold:
            self.click()

    def click(self, button: str = 'left') -> None:
        """
        Perform a mouse click.

        Args:
            button: 'left', 'right', or 'middle'
        """
        if not self.enabled:
            return

        button_map = {
            'left': mouse.Button.left,
            'right': mouse.Button.right,
            'middle': mouse.Button.middle
        }

        if button in button_map:
            self.controller.click(button_map[button])
            self.clicks.append((button, time.time()))

    def get_position(self) -> Tuple[int, int]:
        """
        Get current cursor position in pixels.

        Returns:
            Tuple (x, y) of pixel coordinates
        """
        return self.controller.position

    def get_normalized_position(self) -> np.ndarray:
        """
        Get current cursor position in normalized coordinates [0, 1].

        Returns:
            Array of shape (2,) with normalized position [x, y]
        """
        x, y = self.controller.position
        norm_x = x / self.screen_width
        norm_y = y / self.screen_height
        return np.array([norm_x, norm_y], dtype=np.float32)

    def get_proprioception(self) -> np.ndarray:
        """
        Get proprioceptive feedback for the network.

        This is the sensory signal that reports current cursor position.
        The network compares its prediction against this signal, and the
        resulting error drives cursor movement.

        Returns:
            Array of shape (2,) with normalized cursor position [x, y]
        """
        return self.get_normalized_position()

    def set_position(self, position: Tuple[int, int]) -> None:
        """
        Directly set cursor position (for initialization or testing).

        Args:
            position: Pixel coordinates (x, y)
        """
        if not self.enabled:
            return
        self.controller.position = position

    def enable(self) -> None:
        """Enable motor control."""
        self.enabled = True

    def disable(self) -> None:
        """Disable motor control (safety feature)."""
        self.enabled = False

    def get_movement_stats(self) -> dict:
        """
        Get movement statistics.

        Returns:
            Dictionary with movement metrics
        """
        if len(self.movements) == 0:
            return {'movements': 0, 'avg_speed': 0.0, 'clicks': len(self.clicks)}

        movements_array = np.array([(dx, dy) for dx, dy, _ in self.movements])
        speeds = np.linalg.norm(movements_array, axis=1)

        return {
            'movements': len(self.movements),
            'avg_speed': np.mean(speeds),
            'max_speed': np.max(speeds),
            'clicks': len(self.clicks)
        }

    def __repr__(self) -> str:
        x, y = self.get_position()
        stats = self.get_movement_stats()
        return (f"MouseController(position=({x}, {y}), "
                f"enabled={self.enabled}, "
                f"movements={stats['movements']}, "
                f"clicks={stats['clicks']})")


class KeyboardController:
    """
    Keyboard control via active inference.

    Each key has an associated "error neuron" that fires when the key should
    be pressed. When the error exceeds threshold, the key press is triggered.

    Attributes:
        controller: pynput keyboard controller
        key_thresholds: Dictionary mapping key names to activation thresholds
        enabled: Safety flag to enable/disable keyboard control
    """

    def __init__(
        self,
        key_thresholds: Optional[dict] = None,
        rate_limit_hz: float = 10.0
    ):
        """
        Initialize keyboard controller.

        Args:
            key_thresholds: Dictionary mapping key names to activation thresholds.
                          If None, uses default threshold of 0.7 for all keys
            rate_limit_hz: Maximum key press rate in Hz (per key)
        """
        self.controller = keyboard.Controller()
        self.key_thresholds = key_thresholds or {}
        self.default_threshold = 0.7
        self.rate_limit_hz = rate_limit_hz
        self.min_key_interval = 1.0 / rate_limit_hz

        # Track last press time for each key (rate limiting)
        self.last_press_times = {}

        # Safety flag
        self.enabled = True

        # Statistics
        self.key_presses = deque(maxlen=1000)

    def update_from_signals(self, key_signals: dict) -> None:
        """
        Update keyboard state from key activation signals.

        Args:
            key_signals: Dictionary mapping key names to activation values (0-1).
                        When activation exceeds threshold, key press is triggered.
                        Example: {'space': 0.8, 'enter': 0.3, 'a': 0.1}
        """
        if not self.enabled:
            return

        current_time = time.time()

        for key_name, signal in key_signals.items():
            # Get threshold for this key
            threshold = self.key_thresholds.get(key_name, self.default_threshold)

            # Check if signal exceeds threshold
            if signal > threshold:
                # Rate limiting: check last press time
                last_press = self.last_press_times.get(key_name, 0.0)
                if current_time - last_press >= self.min_key_interval:
                    self.press_key(key_name)
                    self.last_press_times[key_name] = current_time

    def press_key(self, key_name: str) -> None:
        """
        Press and release a key.

        Args:
            key_name: Name of key to press (e.g., 'space', 'enter', 'a')
        """
        if not self.enabled:
            return

        try:
            # Convert key name to pynput key
            key = self._name_to_key(key_name)

            # Press and release
            self.controller.press(key)
            self.controller.release(key)

            # Record
            self.key_presses.append((key_name, time.time()))

        except Exception as e:
            # Handle invalid key names gracefully
            print(f"Warning: Could not press key '{key_name}': {e}")

    def _name_to_key(self, key_name: str):
        """
        Convert key name string to pynput key.

        Args:
            key_name: Name of key (e.g., 'space', 'enter', 'a')

        Returns:
            pynput Key or KeyCode
        """
        # Special keys
        special_keys = {
            'space': keyboard.Key.space,
            'enter': keyboard.Key.enter,
            'return': keyboard.Key.enter,
            'esc': keyboard.Key.esc,
            'escape': keyboard.Key.esc,
            'tab': keyboard.Key.tab,
            'backspace': keyboard.Key.backspace,
            'delete': keyboard.Key.delete,
            'shift': keyboard.Key.shift,
            'ctrl': keyboard.Key.ctrl,
            'alt': keyboard.Key.alt,
            'up': keyboard.Key.up,
            'down': keyboard.Key.down,
            'left': keyboard.Key.left,
            'right': keyboard.Key.right,
        }

        key_lower = key_name.lower()
        if key_lower in special_keys:
            return special_keys[key_lower]

        # Regular character keys
        if len(key_name) == 1:
            return keyboard.KeyCode.from_char(key_name)

        raise ValueError(f"Unknown key name: {key_name}")

    def enable(self) -> None:
        """Enable keyboard control."""
        self.enabled = True

    def disable(self) -> None:
        """Disable keyboard control (safety feature)."""
        self.enabled = False

    def get_key_press_count(self, key_name: Optional[str] = None) -> int:
        """
        Get number of key presses.

        Args:
            key_name: If specified, count only this key. Otherwise count all keys.

        Returns:
            Number of key presses
        """
        if key_name is None:
            return len(self.key_presses)
        return sum(1 for k, _ in self.key_presses if k == key_name)

    def __repr__(self) -> str:
        return (f"KeyboardController(enabled={self.enabled}, "
                f"total_presses={len(self.key_presses)})")


class EmergencyStop:
    """
    Emergency stop system for safety.

    Monitors for a specific key combination (e.g., Ctrl+Shift+Esc) and
    disables all motor control when triggered.
    """

    def __init__(
        self,
        kill_keys: Set[keyboard.Key],
        mouse_controller: MouseController,
        keyboard_controller: KeyboardController,
        callback: Optional[Callable] = None
    ):
        """
        Initialize emergency stop system.

        Args:
            kill_keys: Set of keys that trigger emergency stop when all pressed
            mouse_controller: MouseController to disable on trigger
            keyboard_controller: KeyboardController to disable on trigger
            callback: Optional callback function to execute on trigger
        """
        self.kill_keys = kill_keys
        self.mouse_controller = mouse_controller
        self.keyboard_controller = keyboard_controller
        self.callback = callback

        # Track currently pressed keys
        self.pressed_keys = set()

        # Flag for whether emergency stop has been triggered
        self.triggered = False

        # Start listener
        self.listener = keyboard.Listener(
            on_press=self._on_press,
            on_release=self._on_release
        )
        self.listener.start()

    def _on_press(self, key):
        """Handle key press."""
        self.pressed_keys.add(key)
        self._check_trigger()

    def _on_release(self, key):
        """Handle key release."""
        self.pressed_keys.discard(key)

    def _check_trigger(self):
        """Check if kill keys are all pressed."""
        if not self.triggered and self.kill_keys.issubset(self.pressed_keys):
            self.trigger()

    def trigger(self):
        """Trigger emergency stop."""
        if self.triggered:
            return

        self.triggered = True
        print("\n!!! EMERGENCY STOP TRIGGERED !!!")
        print("All motor control disabled.")

        # Disable controllers
        self.mouse_controller.disable()
        self.keyboard_controller.disable()

        # Execute callback
        if self.callback is not None:
            self.callback()

    def stop(self):
        """Stop the emergency stop listener."""
        self.listener.stop()

    def __repr__(self) -> str:
        key_names = [str(k) for k in self.kill_keys]
        return f"EmergencyStop(keys={key_names}, triggered={self.triggered})"
